version: "3.4"

x-defaults: &defaults
  restart: unless-stopped

services:
  db:
    <<: *defaults
    image: postgres
    networks:
      - db
    expose:
      - "5432"
  app:
    <<: *defaults
    build:
      context: .
      dockerfile: ./compose/development/flask/Dockerfile     
    environment:
      CANDIS_DATABASE_HOST: db
      CANDIS_CACHE_HOST: cache
    networks:
      - db
      - cache
      - proxy
      - node

    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "8888:8888"
        
  cache:
    <<: *defaults
    image: redis
    networks:
      - cache
  proxy:
    <<: *defaults
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    networks:
      - proxy

  node:
    <<: *defaults
    build:
      context: .
      dockerfile: ./compose/development/node/Dockerfile 
    
    depends_on:
      - app
    ports:
      - "9000:9000"
      - "1337:1337"
    networks:
      - node
    environment:
      NODE_ENV: "development"
      NODE_PORT: 9000

networks:
  db:
    driver: bridge
  cache:
    driver: bridge
  proxy:
    driver: bridge 
  node:
    driver: bridge   
