version: "3.4"

x-defaults: &defaults
  restart: unless-stopped

services:
  
  app:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/development/app/Dockerfile
    image: candis-app:development
    container_name: development_candis_app  
    networks:
      - db
      - cache
    depends_on:
      - db
      - cache
    env_file:
      - ./.envs/.development/.app   
    volumes:
      - .:/app
      - development_node_modules:/app/node_modules
      - development_candis_resources:/app/CRES
      - development_candis_data:/app/candisDATA
    ports:
      - "5000:5000"
      - "8888:8888"
  
  db:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/base/db/Dockerfile
    image: candis-db
    container_name: development_candis_db 
    networks:
      - db
    volumes:
      - development_db_data:/var/lib/postgresql/data
      - development_db_backups:/backups
    env_file:
      - ./.envs/.development/.db

  cache:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/base/cache/Dockerfile
    image: candis-cache
    container_name: development_candis_cache
    networks:
      - cache

volumes: 
  development_db_data: {  }
  development_db_backups: { }

  development_node_modules: { }
  development_candis_resources: { }
  development_candis_data: { }
  
networks:
  db:
    driver: bridge
  cache:
    driver: bridge