version: "3.4"

x-defaults: &defaults
  restart: unless-stopped

services:
  db:
    <<: *defaults
    image: postgres
    networks:
      - db
    expose:
      - "5432"
  app:
    <<: *defaults
    build: .
    environment:
      CANDIS_DATABASE_HOST: db
      CANDIS_CACHE_HOST: cache
    networks:
      - db
      - cache
      - proxy

    depends_on:
      - db
    volumes:
      - .:/app      
  cache:
    <<: *defaults
    image: redis
    networks:
      - cache
  proxy:
    <<: *defaults
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    networks:
      - proxy

networks:
  db:
    driver: bridge
  cache:
    driver: bridge
  proxy:
    driver: bridge 
