version: "3.4"

x-defaults: &defaults
  restart: unless-stopped

services:
  db:
    <<: *defaults
    image: postgres
    networks:
      - db
    expose:
      - "5432"
  app:
    <<: *defaults
    build:
      context: .
      dockerfile: ./docker/development/app/Dockerfile
    image: candis-app:development
    container_name: development_candis_app  
    networks:
      - db
      - cache
      - proxy
    depends_on:
      - db
      - cache
    env_file:
      - ./.envs/.development/.app   
    volumes:
      #- .:/app
      - development_node_modules:/app/node_modules
      - development_candis_resources:/app/CRES
      - development_candis_data:/app/candisDATA
    ports:
      - "5000:5000"
      - "8888:8888"
        
  cache:
    <<: *defaults
    image: redis
    networks:
      - cache
  proxy:
    <<: *defaults
    image: nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4000:80"
    networks:
      - proxy

volumes:  
  development_node_modules: { }
  development_candis_resources: { }
  development_candis_data: { }
  
networks:
  db:
    driver: bridge
  cache:
    driver: bridge
  proxy:
    driver: bridge 