const ActionType =
{
  Root:
  {
    RESET_STATE: 'ACTION_TYPE_ROOT_RESET_STATE'
  },

  Defaults:
  {
    UPDATE: 'ACTION_TYPE_DEFAULTS_UPDATE',
    RESTORE: 'ACTIONS_TYPE_DEFAULTS_RESTORE'
  },
  
  App:
  {
     SIGNIN_REQUEST: 'ACTION_TYPE_APP_SIGNIN_REQUEST',
     SIGNIN_SUCCESS: 'ACTION_TYPE_APP_SIGNIN_SUCCESS',
       SIGNIN_ERROR: 'ACTION_TYPE_APP_SIGNIN_ERROR',
           SET_USER: 'ACTION_TYPE_APP_SET_USER',
    SIGNOUT_REQUEST: 'ACTION_TYPE_APP_SIGNOUT_REQUEST',
    SIGNOUT_SUCCESS: 'ACTION_TYPE_APP_SIGNOUT_SUCCESS',
      SIGNOUT_ERROR: 'ACTION_TYPE_APP_SIGNOUT_ERROR'
  },

  Asynchronous:
  {
             WRITE_REQUEST: 'ACTION_TYPE_ASYNCHRONOUS_WRITE_REQUEST',
             WRITE_SUCCESS: 'ACTION_TYPE_ASYNCHRONOUS_WRITE_SUCCESS',
               WRITE_ERROR: 'ACTION_TYPE_ASYNCHRONOUS_WRITE_ERROR',
              READ_REQUEST: 'ACTION_TYPE_ASYNCHRONOUS_READ_REQUEST',
              READ_SUCCESS: 'ACTION_TYPE_ASYNCHRONOUS_READ_SUCCESS',
                READ_ERROR: 'ACTION_TYPE_ASYNCHRONOUS_READ_ERROR',
      GET_RESOURCE_REQUEST: 'ACTION_TYPE_GET_RESOURCE_REQUEST',
      GET_RESOURCE_SUCCESS: 'ACTION_TYPE_GET_RESOURCE_SUCCESS',
        GET_RESOURCE_ERROR: 'ACTION_TYPE_GET_RESOURCE_ERROR',
            DELETE_SUCCESS: 'ACTION_TYPE_ASYNCHRONOUS_DELETE_SUCCESS',
              DELETE_ERROR: 'ACTION_TYPE_ASYNCHRONOUS_DELETE_ERROR'
  },

  Modal:
  {
    SHOW: 'ACTION_TYPE_MODAL_SHOW',
    HIDE: 'ACTION_TYPE_MODAL_HIDE'
  },
  
  DocumentProcessor:
  {
    SET_ACTIVE_DOCUMENT: 'ACTION_TYPE_SET_ACTIVE_DOCUMENT',
              SET_STAGE: 'ACTION_TYPE_DOCUMENT_SET_STAGE'
  },

  DataEditor:
  {
       INSERT_ROW: 'ACTION_TYPE_DATA_EDITOR_INSERT_ROW',
       SELECT_ROW: 'ACTION_TYPE_DATA_EDITOR_SELECT_ROW',
     DESELECT_ROW: 'ACTION_TYPE_DATA_EDITOR_DESELECT_ROW',
       DELETE_ROW: 'ACTION_TYPE_DATA_EDITOR_DELETE_ROW',
       UPDATE_ROW: 'ACTION_TYPE_DATA_EDITOR_UPDATE_ROW',
    INSERT_COLUMN: 'ACTION_TYPE_DATA_EDITOR_INSERT_COLUMN',
    DELETE_COLUMN: 'ACTION_TYPE_DATA_EDITOR_DELETE_COLUMN',
          REFRESH: 'ACTION_TYPE_DATA_EDITOR_REFRESH'
  },

  Entrez: {
            SEARCH: 'ACTION_TYPE_ENTREZ_SEARCH',
          DOWNLOAD: 'ACTION_TYPE_ENTREZ_DOWNLOAD',
    SEARCH_REQUEST: 'ACTION_TYPE_ENTREZ_SEARCH_REQUEST',
  DOWNLOAD_REQUEST: 'ACTION_TYPE_ENTREZ_DOWNLOAD_REQUEST',
      SEARCH_ERROR: 'ACTION_TYPE_ENTREZ_SEARCH_ERROR',
    SEARCH_SUCCESS: 'ACTION_TYPE_ENTREZ_SEARCH_SUCCESS',
    DOWNLOAD_ERROR: 'ACTION_TYPE_ENTREZ_DOWNLOAD_ERROR',
  DOWNLOAD_SUCCESS: 'ACTION_TYPE_ENTREZ_DOWNLOAD_SUCCESS',    
  },

  Pipeline:
  {
    RUN_REQUEST: 'ACTION_TYPE_PIPELINE_RUN_REQUEST',
    RUN_SUCCESS: 'ACTION_TYPE_PIPELINE_RUN_SUCCESS',
      RUN_ERROR: 'ACTION_TYPE_PIPELINE_RUN_ERROR',
DELETE_PIPELINE: 'ACTION_TYPE_PIPELINE_DELETE',
   REMOVE_STAGE: 'ACTION_TYPE_PIPELINE_REMOVE_STAGE'
  },


               INSERT_TOOL: 'ACTION_TYPE_INSERT_TOOL',
             ON_HOVER_TOOL: 'ACTION_TYPE_ON_HOVER_TOOL',
}

export default ActionType
