const ActionType =
{
    SHOW_DIALOG: 'SHOW_DIALOG',
    HIDE_DIALOG: 'HIDE_DIALOG',

     INSERT_ROW: 'INSERT_ROW',
  INSERT_COLUMN: 'INSERT_COLUMN',
    UPDATE_ROWS: 'UPDATE_ROWS'
}

export default ActionType
