"""empty message

Revision ID: cea0c1b73e4e
Revises: cee907d8daae
Create Date: 2018-06-26 12:35:21.520015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea0c1b73e4e'
down_revision = 'cee907d8daae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'random_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('random_column', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
