"""empty message

Revision ID: 189e703ba492
Revises: 
Create Date: 2018-06-18 11:43:13.659661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189e703ba492'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playground')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground',
    sa.Column('equip_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('install_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.CheckConstraint("(location)::text = ANY ((ARRAY['north'::character varying, 'south'::character varying, 'west'::character varying, 'east'::character varying, 'northeast'::character varying, 'southeast'::character varying, 'southwest'::character varying, 'northwest'::character varying])::text[])", name='playground_location_check'),
    sa.PrimaryKeyConstraint('equip_id', name='playground_pkey')
    )
    # ### end Alembic commands ###
