#!/bin/bash

check_status () {
    ps aux | grep $1 | grep -qv grep
    local status=$?

    if [[ ${status} -ne 0 ]]; then
        echo "Error running process $1. Exited with status: ${status}.";
        exit ${status};
    fi
}

app-start &
check_status "app-start"

app-client-start &
check_status "app-client-start"

while sleep 60; do
    check_status "app-start"
    check_status "app-client-start"
done