#!/bin/bash

check_status () {
    ps aux | grep $1 | grep -qv grep
    local status=$?
    # If the grep above find anything, it exit with 0 status
    # If it is not 0, then something is wrong

    if [[ ${status} -ne 0 ]]; then
        echo "Error running process $1. Exited with status: ${status}.";
        exit ${status};
    fi
}

app-start &
check_status "app-start"

app-client-start &
check_status "app-client-start"

The container exits with an error
# if it detects that either of the processes has exited.
# Otherwise it loops forever, waking up every 60 seconds

while sleep 60; do
    check_status "app-start"
    check_status "app-client-start"
done