"""empty message

Revision ID: cee907d8daae
Revises: aaa528926e92
Create Date: 2018-06-26 12:32:06.331636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee907d8daae'
down_revision = 'aaa528926e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('random_column', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'random_column')
    # ### end Alembic commands ###
